export const Denomination_data = [

    {value:'Anglican/Episcopal',},
    {value:'Apostolic',},
    {value:'Assembly of God (AG)',},
    {value:'Baptist',},
    {value:'Born Again',},
    {value:'Brethren',},
    {value:'Calvinist',},
    {value:'Catholic',},
    {value:'Church of God',},
    {value:'Church of Christ',},
    {value:'Church of North India',},
    {value:'Congregational',},
    {value:'East Indian Catholic',},
    {value:'Evangelical',},
    {value:'Knanayan Catholic',},
    {value:'Jehovah Witness',},
    {value:'Lutheran',},
    {value:'Mennonite',},
    {value:'Methodist',},
    {value:'Orthodox',},
    {value:'Pentecostal',},
    {value:'Protestant',},
    {value:'Reformed Baptist',},
    {value:'St. Thomas Evangelical',},
    {value:'Syrian Catholic',},
    {value:'Others'},
    

]